[package]
name = "fastrapi"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastrapi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module", "py-clone", "abi3-py39"]}
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }
axum = "0.8.6"
dashmap = "6.1.0"
once_cell = "1.21.3"
serde_json = "1.0.145"
serde-pyobject = "0.8.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
utoipa-swagger-ui = { version = "9", features = ["axum"] }
serde = "1.0.228"
num_cpus = "1.17.0"
smallvec = "1.15.1"
smartstring = "1.0.1"
tokio-tungstenite = "0.28.0"
futures-util = "0.3.31"
utoipa = "5.4.0"
hyper = "1.7.0"
hyper-util = "0.1.17"
# TODO: if using python package, make these features optional
tower-http = {version ="0.6.6", features = ["cors", "trace", "set-header", "compression-gzip"] }
tower-sessions = {version ="0.14.0", features = ["signed"]} # for sessions
tower = "0.5.2"
cookie = {version = "0.18.1",features = ["private", "signed"]}
pythonize = "0.27.0"
papaya = { version = "0.2.3" }
parking_lot = "0.12.5"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
opt-level = 3

[profile.release.build-override]
opt-level = 3
